#!/usr/bin/env bash 
NAME="Tsedal"
echo "Hello $NAME!"
string="HELLO GUYS LET US CHAT"
if [[ -z "$string" ]]; then
  echo "String is empty"
elif [[ -n "$string" ]]; then
  echo "String is not empty"
fi

fruit=('Ornange' 'Apple' 'Banana' 'Strob');

for fr in "${fruit[@]}";
do
echo $fr
done
